name: Build

on:
  push:
    branches:
      - master
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-22.04
    name: Build
    env:
      TEXMFHOME: /home/runner/work/unnamed-emoji/unnamed-emoji/texmf/

    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v3

      - name: Install TeX Live
        uses: zauguin/install-texlive@v3
        with:
          packages: >
            context
            iftex
            infwarerr
            latex
            latex-bin
            libertinus-fonts
            ltxcmds
            luatex85
            optex
            pdftexcmds
            plex
            standalone
            tex-gyre
            tex-gyre-math

      - name: Build the documentation
        run: |
          export PATH=$HOME/texlive/bin/x86_64-linux:$PATH
          sed -i '/registerfontmethod/,+4!b;{s/--/  /}' "$(kpsewhich lpdf-emb.lmt)"

          mtxrun --generate > /dev/null
          context --make > /dev/null

          cd "$GITHUB_WORKSPACE/documentation"
          wget "https://raw.githubusercontent.com/gucci-on-fleek/lua-widow-control/master/docs/manual/lwc-manual.mkxl"
          context unemoji-manual

      - name: Bundle the package
        run: |
          cd "$GITHUB_WORKSPACE"/texmf
          zip -r "$GITHUB_WORKSPACE"/unnamed-emoji.tds.zip ./*
          mkdir "$GITHUB_WORKSPACE"/ctan && cd "$GITHUB_WORKSPACE"/ctan
          mkdir unnamed-emoji
          find -L "$GITHUB_WORKSPACE"/texmf -type f -exec cp '{}' unnamed-emoji \;
          cp "$GITHUB_WORKSPACE"/unnamed-emoji.tds.zip .
          zip -r "$GITHUB_WORKSPACE"/unnamed-emoji.ctan.zip ./*

      - name: Archive on success
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: build-result
          retention-days: 7
          if-no-files-found: error
          path: |
            unnamed-emoji.tds.zip
            documentation/unemoji-manual.pdf

      - name: Create a release if this is a tag
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          fail_on_unmatched_files: true
          files: |
            texmf/doc/generic/unnamed-emoji/unnamed-emoji.pdf
            texmf/doc/generic/unnamed-emoji/unnamed-emoji-specimens.pdf
            unnamed-emoji.ctan.zip
            unnamed-emoji.tds.zip
